server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/study
    username: testuser
    password: testpass
    
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
 
