server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://
    username: refficstest
    password: 
    
mybatis:
  config-location: 
    classpath:mybatis-config.xml 
  mapper-locations:
  - classpath:mapper/*/*.xml
 
